CREATE TABLE IF NOT EXISTS perfect_music (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author varchar(255) not null,
    title varchar(255) not null
);


create sequence perfect_music_sequence start with 1 increment by 1;

insert into perfect_music (author, title) values ('Coldplay', 'Fix you');
insert into perfect_music (author, title) values ('Coldplay', 'Paradise');